export type ToolCategory =
  | "all"
  | "organize"
  | "convert"
  | "edit"
  | "security";

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: Exclude<ToolCategory, "all">;
  icon: string;
  color: string;
  bg: string;
  badge?: "new" | "hot";
  accept: string;
  multiple: boolean;
  actionLabel: string;
}

export const TOOLS: Tool[] = [
  // Organize
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one document",
    category: "organize",
    icon: "📑",
    color: "#4F46E5",
    bg: "#EEF2FF",
    accept: ".pdf",
    multiple: true,
    actionLabel: "Merge PDFs",
  },
  {
    id: "split",
    name: "Split PDF",
    description: "Divide a PDF into separate pages or ranges",
    category: "organize",
    icon: "✂️",
    color: "#0891B2",
    bg: "#ECFEFF",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Split PDF",
  },
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce file size while keeping quality",
    category: "organize",
    icon: "🗜️",
    color: "#D97706",
    bg: "#FFFBEB",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Compress PDF",
  },
  {
    id: "remove-pages",
    name: "Remove Pages",
    description: "Delete specific pages from your PDF",
    category: "organize",
    icon: "🗑️",
    color: "#DC2626",
    bg: "#FEF2F2",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Remove Pages",
  },
  {
    id: "extract-pages",
    name: "Extract Pages",
    description: "Pull out selected pages into a new PDF",
    category: "organize",
    icon: "📤",
    color: "#7C3AED",
    bg: "#F5F3FF",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Extract Pages",
  },
  // Convert
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF to an editable Word document",
    category: "convert",
    icon: "📝",
    color: "#1D4ED8",
    bg: "#EFF6FF",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Convert to Word",
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert each PDF page to an image",
    category: "convert",
    icon: "🖼️",
    color: "#059669",
    bg: "#ECFDF5",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Convert to JPG",
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract tables from PDF into a spreadsheet",
    category: "convert",
    icon: "📊",
    color: "#16A34A",
    bg: "#F0FDF4",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Convert to Excel",
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Turn a Word document into a PDF",
    category: "convert",
    icon: "📄",
    color: "#D97706",
    bg: "#FFFBEB",
    accept: ".doc,.docx",
    multiple: false,
    actionLabel: "Convert to PDF",
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Combine images into a single PDF",
    category: "convert",
    icon: "🖼️",
    color: "#DC2626",
    bg: "#FEF2F2",
    accept: "image/*",
    multiple: true,
    actionLabel: "Convert to PDF",
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert a web page or HTML file to PDF",
    category: "convert",
    icon: "🌐",
    color: "#7C3AED",
    bg: "#F5F3FF",
    accept: ".html,.htm",
    multiple: false,
    actionLabel: "Convert to PDF",
    badge: "new",
  },
  // Edit
  {
    id: "remove-bg",
    name: "Remove Background",
    description: "Remove background from any image instantly",
    category: "edit",
    icon: "🪄",
    color: "#7C3AED",
    bg: "#F5F3FF",
    accept: "image/*",
    multiple: false,
    actionLabel: "Remove Background",
    badge: "new" as const,
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate one or all pages to any angle",
    category: "edit",
    icon: "🔄",
    color: "#4F46E5",
    bg: "#EEF2FF",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Rotate PDF",
  },
  {
    id: "watermark",
    name: "Add Watermark",
    description: "Stamp text or image on your PDF pages",
    category: "edit",
    icon: "💧",
    color: "#0891B2",
    bg: "#ECFEFF",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Add Watermark",
  },
  {
    id: "page-numbers",
    name: "Page Numbers",
    description: "Add auto page numbers to any PDF",
    category: "edit",
    icon: "🔢",
    color: "#059669",
    bg: "#ECFDF5",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Add Page Numbers",
  },
  {
    id: "summarize",
    name: "AI Summarize",
    description: "Get an intelligent summary of your PDF",
    category: "edit",
    icon: "✨",
    color: "#7C3AED",
    bg: "#F5F3FF",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Summarize PDF",
    badge: "hot",
  },
  // Security
  {
    id: "protect",
    name: "Protect PDF",
    description: "Lock your PDF with a password",
    category: "security",
    icon: "🔒",
    color: "#4F46E5",
    bg: "#EEF2FF",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Protect PDF",
  },
  {
    id: "unlock",
    name: "Unlock PDF",
    description: "Remove password protection from a PDF",
    category: "security",
    icon: "🔓",
    color: "#DC2626",
    bg: "#FEF2F2",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Unlock PDF",
  },
  {
    id: "sign",
    name: "Sign PDF",
    description: "Add your digital signature to a document",
    category: "security",
    icon: "✍️",
    color: "#059669",
    bg: "#ECFDF5",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Sign PDF",
    badge: "new",
  },
  {
    id: "redact",
    name: "Redact PDF",
    description: "Permanently hide sensitive content",
    category: "security",
    icon: "🚫",
    color: "#D97706",
    bg: "#FFFBEB",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Redact PDF",
  },
  {
    id: "edit-pdf",
    name: "Edit PDF",
    description: "Add text, images and shapes directly onto your PDF",
    category: "edit",
    icon: "✏️",
    color: "#0891B2",
    bg: "#ECFEFF",
    accept: ".pdf",
    multiple: false,
    actionLabel: "Save Edited PDF",
    badge: "new" as const,
  },
];

export const CATEGORIES: { id: ToolCategory; label: string }[] = [
  { id: "all", label: "All tools" },
  { id: "organize", label: "Organize" },
  { id: "convert", label: "Convert" },
  { id: "edit", label: "Edit" },
  { id: "security", label: "Security" },
];
